#-------------------------------Training iteration1-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration1.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration1_x10.txt
echo 'Training over';
#------------------------------Training of iteration1 Over-------------------------------------------------------------------
#-------------------------------Testing iteration1-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set1.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration1.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration1.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration1.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset1 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion1.txt
#-------------------------------------------1st iteration over--------------------------------------------------------------
#-------------------------------Training iteration2-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration2.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration2_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration2-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set2.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration2.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration2.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration2.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset2 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion2.txt
#-------------------------------------------2nd iteration over--------------------------------------------------------------
#-------------------------------Training iteration3-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration3.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration3_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration3-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set3.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration3.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration3.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration3.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset3 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion3.txt
#-------------------------------------------3rd iteration over--------------------------------------------------------------
#-------------------------------Training iteration4-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration4.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration4_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration2-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set4.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration4.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration4.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration4.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset4 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion4.txt
#-------------------------------------------4th iteration over--------------------------------------------------------------
#-------------------------------Training iteration5-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration5.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration5_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration2-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set5.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration5.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration5.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration5.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset5 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion5.txt
#-------------------------------------------5th iteration over--------------------------------------------------------------
#-------------------------------Training iteration6-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration6.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration6_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration2-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set6.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration6.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration6.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration6.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset6 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion6.txt
#-------------------------------------------6th iteration over--------------------------------------------------------------
#-------------------------------Training iteration7-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration7.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration7_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration7-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set7.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration7.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration7.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration7.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset7 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion7.txt
#-------------------------------------------7th iteration over--------------------------------------------------------------
#-------------------------------Training iteration8-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration8.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration8_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration2-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set8.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration8.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration8.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration8.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset8 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion8.txt
#-------------------------------------------8th iteration over--------------------------------------------------------------
#-------------------------------Training iteration9-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration9.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration9_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration9-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set9.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration9.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration9.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration9.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset9 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion9.txt
#-------------------------------------------1st iteration over--------------------------------------------------------------
#-------------------------------Training iteration2-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration10.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration10_x10.txt
#------------------------------ Training  Over-------------------------------------------------------------------
#-------------------------------Testing iteration2-----------------------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set10.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration10.model -p 0  > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration10.txt
#-------------------------------Testing over-------------------------------------------------------------------------------
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/SVM_iteration10.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset10 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion10.txt
#-------------------------------------------1oth iteration over--------------------------------------------------------------
#-------------------------------Training iteration11-----------------------------------------------------------
java -classpath /usr/share/java/weka.jar:/usr/share/java/libsvm.jar weka.classifiers.meta.FilteredClassifier -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -x 10 -c last -i -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/SVMx10_iteration11.model -F 'weka.filters.unsupervised.attribute.StringToWordVector -R 1 -W 3000 -N 0 -stemmer weka.core.stemmers.NullStemmer -T -I -M 1 -tokenizer weka.core.tokenizers.WordTokenizer -C'  -W weka.classifiers.functions.LibSVM >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/SVM_iteration11_x10.txt
