export CLASSPATH=/usr/share/java/weka.jar;
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/trainingSetforAtemporal-TemporalOneStep.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set.arff  -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set1.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
echo 'STW 1st over';
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_reordered.arff
echo '1st reordering over';
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i    /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1.arff -o   /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_reordered.arff 
echo '2nd reordering over';
#1st iteration of training --Train Naive Bayes on ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration1.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration1_TS_x10.txt #TS=Training set
echo '1st training over';
#--------------------------------------------------------1st iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------1st iteration of Testing Begins----------------------------------

#------------------------------------------------------------Testing on set 1------------------------------------
#Test on ngram_data_output_set1.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_reordered.arff -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration1.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet1_NaiveBayes_iteration1.txt
echo '1st testing over';
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet1_NaiveBayes_iteration1.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset1 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8
echo '1st expansion over';
#-----------------------------------------------------STW on new training set tto produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration1.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set2.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set2.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration1.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration1_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set2.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set2_reordered.arff
echo '1st iteration over'
#2nd iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration1_reordered.arff  -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration2.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration2_TS_x10.txt
#--------------------------------------------------------2nd iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------2nd iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 2------------------------------------
#                                 Test on ngram_data_output_set2.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set2_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration2.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet2_NaiveBayes_iteration2.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar  FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet2_NaiveBayes_iteration2.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset2 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration2.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set3.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set3.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration2.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration2_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set3.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set3_reordered.arff
echo '2nd iteration over'
#3rd iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration2_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration3.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration3_TS_x10.txt
#--------------------------------------------------------3rd iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------3rd iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 3------------------------------------
#                                 Test on ngram_data_output_set3.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set3_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration3.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet3_NaiveBayes_iteration3.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar   FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet3_NaiveBayes_iteration3.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset3 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration3.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set4.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set4.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration3.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration3_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set4.arff -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set4_reordered.arff 
echo '3rd iteration over'
#4th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration3_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration4.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration4_TS_x10.txt
#--------------------------------------------------------4th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------4th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 4-----------------------------------
#                                 Test on ngram_data_output_set4.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set4_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration4.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet4_NaiveBayes_iteration4.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet4_NaiveBayes_iteration4.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset4 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration4.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set5.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set5.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration4.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration4_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set5.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set5_reordered.arff
echo '4th iteration over'
#5th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration4_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration5.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration5_TS_x10.txt
#--------------------------------------------------------5th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------5th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 5-----------------------------------
#                                 Test on ngram_data_output_set5.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set5_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration5.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet5_NaiveBayes_iteration5.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet5_NaiveBayes_iteration5.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset5 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration5.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set6.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set6.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration5.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration5_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set6.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set6_reordered.arff 
echo '5th iteration over'
#6th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration5_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration6.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration6_TS_x10.txt
#--------------------------------------------------------6th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------6th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 6-----------------------------------
#                                 Test on ngram_data_output_set6.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp  /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set6_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration6.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet6_NaiveBayes_iteration6.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet6_NaiveBayes_iteration6.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset6 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration6.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set7.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set7.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration6.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration6_reordered.arff 
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set7.arff   -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set7_reordered.arff 
echo '6th iteration over'
#7th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration6_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration7.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration7_TS_x10.txt
#--------------------------------------------------------7th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------7th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 7-----------------------------------
#                                 Test on ngram_data_output_set7.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set7_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration7.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet7_NaiveBayes_iteration7.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar  FindInstancesForProbabilisticExpansion  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet7_NaiveBayes_iteration7.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset7 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8 
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration7.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set8.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set8.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration7.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration7_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set8.arff   -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set8_reordered.arff
echo '7th iteration over'
#8th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration7_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration8.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration8_TS_x10.txt
#--------------------------------------------------------8th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------8th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 8-----------------------------------
#                                 Test on ngram_data_output_set8.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set8_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration8.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet8_NaiveBayes_iteration8.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet8_NaiveBayes_iteration8.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset8 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration8.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set9.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set9.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration8.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration8_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set9.arff   -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set9_reordered.arff 
echo '8th iteration over'
#9th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration8_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration9.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration9_TS_x10.txt
#--------------------------------------------------------9th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------9th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 9-----------------------------------
#                                 Test on ngram_data_output_set9.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set9_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration9.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet9_NaiveBayes_iteration9.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet9_NaiveBayes_iteration9.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset9 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_iteration1.txt 8
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalOneStep_iteration1.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration9.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set10.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set10.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
echo '9th iteration over'
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration9.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration9_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set10.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set10_reordered.arff
#10th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalOneStep_set_iteration9_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration10.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration10_TS_x10.txt
#--------------------------------------------------------10th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------10th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 10-----------------------------------
#                                 Test on ngram_data_output_set10.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set10_reordered.arff -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx6Training_iteration10.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet10_NaiveBayes_iteration10.txt
echo '10th iteration over'

