export CLASSPATH=/usr/share/java/weka.jar;
#----------------------------------------------------STW----------------------------------------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration1_2ndtime.arff  -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set1.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
echo 'STW 1st over';
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration1_2ndtime.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration1_2ndtime_reordered.arff
echo '1st reordering over';
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i    /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_2ndtime.arff -o   /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_2ndtime_reordered.arff 
echo '2nd reordering over';
#1st iteration of training --Train Naive Bayes on ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TrainingData/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration1_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration1_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration1_TS_x10_2ndtime.txt #TS=Training set
echo '1st training over';
#--------------------------------------------------------1st iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------1st iteration of Testing Begins----------------------------------

#------------------------------------------------------------Testing on set 1------------------------------------
#Test on ngram_data_output_set1.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_2ndtime_reordered.arff -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration1_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet1_NaiveBayes_iteration1_2ndtime.txt
echo '1st testing over';
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet1_NaiveBayes_iteration1_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset1 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion1_2ndtime.txt
echo '1st expansion over';
#-----------------------------------------------------STW on new training set tto produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration2_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set2.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set2_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration2_2ndtime.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration2_2ndtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set2_2ndtime.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set2_2ndtime_reordered.arff
echo '1st iteration over'
#2nd iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration2_2ndtime_reordered.arff  -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration2_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration2_TS_x10_2ndtime.txt
#--------------------------------------------------------2nd iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------2nd iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 2------------------------------------
#                                 Test on ngram_data_output_set2.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set2_2ndtime_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration2_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet2_NaiveBayes_iteration2_2ndtime.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar  FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet2_NaiveBayes_iteration2_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset2 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion2_2ndtime.txt
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration3_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set3.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set3_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration3_2ndtime.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration3_2ndtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set3_2ndtime.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set3_2ndtime_reordered.arff
echo '2nd iteration over'
#3rd iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration3_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration3_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration3_TS_x10_2ndtime.txt
#--------------------------------------------------------3rd iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------3rd iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 3------------------------------------
#                                 Test on ngram_data_output_set3.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set3_2ndtime_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration3_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet3_NaiveBayes_iteration3_2ndtime.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar   FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet3_NaiveBayes_iteration3_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset3 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion3_2ndtime.txt
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration4_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set4.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set4_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration4_2ndtime.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration4_2ndtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set4_2ndtime.arff -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set4_2ndtime_reordered.arff 
echo '3rd iteration over'
#4th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration4_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration4_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration4_TS_x10_2ndtime.txt
#--------------------------------------------------------4th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------4th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 4-----------------------------------
#                                 Test on ngram_data_output_set4.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set4_2ndtime_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration4_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet4_NaiveBayes_iteration4_2ndtime.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet4_NaiveBayes_iteration4_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset4 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion4_2ndtime.txt
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration5_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set5.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set5_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration5_2ndtime.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration5_2ndtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set5_2ndtime.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set5_2ndtime_reordered.arff
echo '4th iteration over'
#5th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration5_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration5_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration5_TS_x10_2ndtime.txt
#--------------------------------------------------------5th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------5th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 5-----------------------------------
#                                 Test on ngram_data_output_set5.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set5_2ndtime_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration5_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet5_NaiveBayes_iteration5_2ndtime.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet5_NaiveBayes_iteration5_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset5 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion5_2ndtime.txt
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration6_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set6.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set6_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration6_2ndtime.arff -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration6_2ndtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set6_2ndtime.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set6_2ndtime_reordered.arff 
echo '5th iteration over'
#6th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration6_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration6_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration6_TS_x10_2ndtime.txt
#--------------------------------------------------------6th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------6th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 6-----------------------------------
#                                 Test on ngram_data_output_set6.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp  /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set6_2ndtime_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration6_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet6_NaiveBayes_iteration6_2ndtime.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet6_NaiveBayes_iteration6_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset6 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion6_2ndtime.txt
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration7_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set7.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set7_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration7_2ndtime.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration7_2ndtime_reordered.arff 
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set7_2ndtime.arff   -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set7_2ndtime_reordered.arff 
echo '6th iteration over'
#7th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration7_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration7_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration7_TS_x10_2ndtime.txt
#--------------------------------------------------------7th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------7th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 7-----------------------------------
#                                 Test on ngram_data_output_set7.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set7_2ndtime_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration7_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet7_NaiveBayes_iteration7_2ndtime.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar  FindInstancesForProbabilisticExpansion  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet7_NaiveBayes_iteration7_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset7 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion7_2ndtime.txt 
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration8_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set8.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set8_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration8_2ndtime.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration8_2ndtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set8_2ndtime.arff   -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set8_2ndtime_reordered.arff
echo '7th iteration over'
#8th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration8_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration8_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration8_TS_x10_2ndtime.txt
#--------------------------------------------------------8th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------8th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 8-----------------------------------
#                                 Test on ngram_data_output_set8.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set8_2ndtime_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration8_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet8_NaiveBayes_iteration8_2ndtime.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet8_NaiveBayes_iteration8_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset8 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion8_2ndtime.txt
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration9_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set9.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set9_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration9_2ndtime.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration9_2ndtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set9_2ndtime.arff   -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set9_2ndtime_reordered.arff 
echo '8th iteration over'
#9th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration9_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration9_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration9_TS_x10_2ndtime.txt
#--------------------------------------------------------9th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------9th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 9-----------------------------------
#                                 Test on ngram_data_output_set9.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set9_2ndtime_reordered.arff  -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration9_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet9_NaiveBayes_iteration9_2ndtime.txt
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet9_NaiveBayes_iteration9_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset9 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion9_2ndtime.txt
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration10_2ndtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set10.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set10_2ndtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
echo '9th iteration over'
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration10_2ndtime.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration10_2ndtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set10_2ndtime.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set10_2ndtime_reordered.arff
#10th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration10_2ndtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration10_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration10_TS_x10_2ndtime.txt
#--------------------------------------------------------10th iteration of Training Over-------------------------------
#-----------------------------------------------------------------------------------------------------------
#--------------------------------------------------------10th iteration of Testing Begins----------------------------------
#------------------------------------------------------------Testing on set 10-----------------------------------
#                                 Test on ngram_data_output_set10.arff using saved NaiveBayes model
#----------------------------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -T /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set10_2ndtime_reordered.arff -l /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration10_2ndtime.model -p 0 > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet10_NaiveBayes_iteration10_2ndtime.txt
echo '10th iteration over'
#-------------------------------------------------------Expansion of training set------------------
java -cp /home/dipawesh/workspace/Hindi_wordnet_time_tagging/src/FindInstancesForProbabilisticExpansion.jar FindInstancesForProbabilisticExpansion /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Predictions/Prediction_2-3GramDataOutputSet10_NaiveBayes_iteration10_2ndtime.txt /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/dataset10 /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/Temporal_atemporal_seed_words_2Class.txt 8 >/home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expansion1_Details/Expansion10_2ndtime.txt
#-----------------------------------------------------STW on new training set to produce file with 2 or 3 grams--------------------------
java -classpath /usr/share/java/weka.jar weka.filters.unsupervised.attribute.StringToWordVector -b -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/0gram/trainingSetforAtemporal-TemporalTwoStep_2Class.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration1_3rdtime.arff -c last -r /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/ngram_data_set1.arff -s  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_3rdtime.arff -R 1,2 -O -C -T -I -N 0 -M 1 -tokenizer weka.core.tokenizers.WordTokenizer
echo '11th iteration over'
#---------------------------------------Reordering----------------------------------------
#-------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration1_3rdtime.arff  -o  /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration1_3rdtime_reordered.arff
#--------------------------------------------------------------------------------------------------
java weka.filters.unsupervised.attribute.Reorder -R 2-last,1  -i /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_3rdtime.arff  -o /home/dipawesh/workspace/Hindi_wordnet_time_tagging/TestData/DatasetInChunks/Ngram/ngram_data_output_set1_3rdtime_reordered.arff
#10th iteration of training --Train Naive Bayes on udated ngram_trainingSetforAtemporal-TemporalOneStep_set with x=5 
#---------------------------------------------------------------------------------------
java -cp /usr/share/java/weka.jar weka.classifiers.bayes.NaiveBayes -t /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Expanded_Training_data/NaiveBayes/Ngram/ngram_trainingSetforAtemporal-TemporalTwoStep_2Class_iteration1_3rdtime_reordered.arff -x 10 -c last -i -K -d /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Models/OneStep/NaiveBayesx10Training_iteration11_2ndtime.model > /home/dipawesh/workspace/Hindi_wordnet_time_tagging/Performance/NaiveBayes_iteration11_TS_x10_2ndtime.txt
echo 'Process over';
#------------------------------------------------------------------------------------------------------------------------

